fga-eps-mds/2021.2-Sigaa-Plus

docs/DocumentoDeVisao.md

Adicionando a tabela do tópico  3.1 do documento de visão.

Adição do tópico 3.1 do documento

---

docs/DocumentoDeVisao.md

Adicionando mais informações no tópico 1.1

Edição do tópico 1.1

---

README.md
docs/TAP.md
docs/sprints/sprint1/Planejamento.md

* Documento de planejamento da sprint 1
* Ajustes

Documentação de planejamento da sprint 1

---

docs/TAP.md

* Adicionando cronograma no documento

documentando termo de abertura de projeto 

---

docs/sprints/sprint2/Planejamento.md
docs/sprints/sprint2/Resultado.md

Ajuste na documentação da sprint 2
Correção Sprint 2 https://github.com/fga-eps-mds/Tema-02/issues/60

FIX (Issue #60): fazendo ajuste na documentação da sprint 2

---

docs/DocumentoDeRequisitos.md

Elaboração do documento de requisitos de software
#67

Documento de Requisitos

---

docs/sprints/sprint5/TimeA/planejamento.md
docs/sprints/sprint5/TimeB/planejamento.md

Adição do planejamento da Sprint 05 por times.
-[ ] Criação de duas pastas para planejamento da Sprint 05 para o time A e o time B
-[ ] Criação do documento de planejamento da Sprint 05 dos dois times
A issue que foi resolvida foi a issue #81 

ADD (Issue #81): Planejamento da Sprint 05

---

docs/DocumentoDeVisao.md

Atualização do documento de visão
-[ ] Realizar alterações no documento de visão

[DOC] (Issue #91) : Atualizando o documento de visão

---

docs/DocumentoDeArquitetura.md

Adição do tópico 4
Inserido tópico: Visão de Casos de Uso
Resolve a Issue #98

[DOC] Issue #98 : add Visão de Casos de Uso

---

docs/sprints/sprint5/TimeA/Resultado.md
docs/sprints/sprint5/TimeA/planejamento.md
docs/sprints/sprint5/TimeB/Resultado.md
docs/sprints/sprint5/TimeB/planejamento.md

Foi atualizado o quadro de pontos do planejamento da Sprint 05 e foi adicionado o resultado da Sprint 05.
-[ ] Planejamento da Sprint 05
-[ ] Resultado da Sprint 05
#81 

[ADD] (Issue #81): adicionando resultado da Sprint 05

---

docs/DocumentoDoRoadmap.md

Criação do documento do roadmap
-[ ] Criar documento
-[ ] Adicionar a tabela do projects

[DOC] (Issue #105) : Criação do documento do roadmap

---

docs/DocumentoDoRoadmap.md

Adicionando imagem do Roadmap
-[ ] Adicionar imagem do Roadmap

[ADD] (Issue #105) : Adicionando imagem do Roadmap

---

docs/DocumentoDeVisao.md

Concertar erros na estrutura do documento
-[ ] Analisar e concertar erros na estrutura do documento

[FIX] (Issue #91) : Concertando erros na estrutura do documento

---

docs/DocumentoDeVisao.md

Removendo parte de requisitos do documento 
-[ ] Remover parte de requisitos do documento 
#112 

[FIX] (Issue #112) : Edição do documento de visão

---

docs/Ferramentas.md

Elaboração do documento de ferramentas utilizadas.
Issue #113

[DOC] (Issue #113): Abertura do documento de ferramentas utilizadas

---

docs/TAP.md

Atualizando TAP com tópicos pendentes.
Issue #120

[DOC] (Issue #120): Atualizando Termo de Abertura do Projeto

---

docs/DocumentoDeMetodologia.md

Foi atualizado o documento de metodologia
A Issue #118

 [DOC] (Issue #118) : adição de conteúdo nos tópicos 4, 5 e 6

---

docs/DocumentoDeMetodologia.md

adição de conteúdos nos tópicos 1, 2 e 3
adição de conteúdos nos tópicos 1, 2 e 3
Resolve a Issue #122

[DOC] issue #122: adição de conteúdos nos tópicos 1, 2 e 3

---

docs/sprints/sprint7/Time B/Planejamento.md

Confecção de documento de planejamento da sprint 7 do time B.
Issue #148

[DOC] (Issue #148): Planejamento Sprint 7 - Time B

---

docs/DocumentoDeRequisitos.md
docs/DocumentoDeVisao.md

Especificando usuário do produto
-[ ] Especificar usuário do produto para melhor entendimento
#157 

[FIX] (Issue #157) : Especificando usuário do produto

---

docs/DocumentoDeComunicação.md
docs/DocumentoDeMetodologia.md

Criação do Documento de comunicação e dos tópicos "introdução" e "ferramentas e Rituais"
Descrição
Descrever de forma objetiva e coerente o que foi feito
Criação do Documento de comunicação e dos tópicos "introdução" e "ferramentas e Rituais"
Descrever de forma objetiva e coerente o que foi feito
Issues que foram resolvidas com o pull request

[DOC] (Issue #152): Atualização do plano de comunicação do Projeto

---

docs/sprints/sprint6/TimeA/planejamento.md

Documentação pendente da Sprint 06 do Time A
#165

[DOC](Issue #106): planejamento pendente da Sprint 06

---

docs/sprints/sprint6/Time B/Planejamento.md
docs/sprints/sprint6/Time B/Resultado.md

Elaboração da documentação pendente da Sprint 6
Issue #173

[DOC] (Issue #173): Realizando documentação pendente da Sprint 6

---

StyleGuide.md

Escrever a sessão de componentes do documento style guide.
#177

Componentes style guide

---

api/services/scraping/equivalencias.json
api/services/scraping/webScraping.js
package.json

Atualização do RF01, expandindo captura de dados para todos os departamentos da UnB, e armazenando todas as informações capturados em  um arquivo JSON 
-[ ] Expansão da captura de dados, relacionados as matérias equivalentes
-[ ] Organização dos dados em arquivos JSON
#182

Feature RF01

---

api/services/scraping/equivalencias.json
api/services/scraping/webScraping.js
package.json

Reverts fga-eps-mds/2021.2-Sigaa-Plus#184

Revert "Revert "Feature RF01""

---

docs/sprints/sprint9/TimeA/Planejamento.md

Após o problema em relação à mesclagem, foi criada uma nova branch com o planejamento da Sprint 09.
Issues que foram resolvidas com o pull request

[DOC](issue #192): planejamento da Sprint 09

---

api/routes/routes.js

Criação de api para integração do Back-end da RF01
Foi criado uma api para integração do Back-end da RF01
#227 #231

[UPDATE](Issue #227 #231): api integração do Back-end

---

src/App.vue
src/components/telaRF2.vue

Suporte do Time A para o Time B e a criação dos componentes visuais da RF2
A Issue #226

Suporte ao front-end para a criação de componentes visuais referentes à RF2.

---

package-lock.json
src/components/telaGraficos.vue

Desenvolvimento da tela de gráficos por crédito
Issue #214

[ADD] (Issue #214): Desenvolvimento tela de gráficos

---

src/App.vue
src/components/telaGraficos.vue
src/components/telaRF1_parte1.vue
src/components/telaRF1_parte2.vue
src/components/telaRF2.vue

Correção no CSS dos componentes visuais
Issue #249

[FIX] (Issue #249): Corrigindo css nos componentes visuais

---

docs/sprints/sprint10/Time A/Resultado.md
docs/sprints/sprint11/TimeA/Resultado.md
docs/sprints/sprint9/Time A/Resultado.md

Documento review sprint 11
Issues que foram resolvidas com o pull request

Feature review sprint11

---

docs/sprints/sprint12/TimeA/Planejamento.md

Criação do documento de planejamento da Sprint 12 e quadro de presença da reunião de planejamento. O quadro se encontra dentro da documentação.
#252

[#DOC](Issue #253): criação do documento de planejamento da Sprint 12

---

docs/sprints/sprint12/TimeA/Resultado.md

 [DOC] (Issue #254) : review sprint 12

---

api/services/scraping/materiasCursadas.js

1/3 da integração de disciplinas cursadas
#228

Feature rf02 disciplinas cursadas

---

api/services/scraping/materiasCursadas.js

Botão para acionar a função salvar matérias

 [FIX] (Issue #228) : criando botão

---

docs/sprints/sprint11/TimeB/Planejamento.md
docs/sprints/sprint11/TimeB/Resultado.md
docs/sprints/sprint12/TimeB/Planejamento.md
docs/sprints/sprint12/TimeB/Resultado.md
docs/sprints/sprint13/TimeB/Planejamento.md

Criação dos documentos das sprints 11, 12 e 13
Issues resolvidas - #243, #279, #278

Documentação de sprints pendentes

---

docs/sprints/sprint13/Time A/Planejamento.md

Documento de planejamento da Sprint 13 e quadro de presença da reunião de planejamento.
#261

[DOC](Issue #261): documento de planejamento da Sprint 13

---

src/components/telaRF2.vue

Corrigindo estilo dos componentes da RF02
#274

 [REFACT] (Issue #274) : correção e refatoração

---

package-lock.json
package.json
src/components/telaRF2.vue
src/cursoDoUsuario.js
src/details/Contentscript.js
src/materiasCursadas.js

Comparando matérias cursadas
Issues que foram resolvidas com o pull request

 [ADD] (Issue: #228) : Comparando materias cursadas

---

src/components/telaRF2.vue

Refatoração do código anterior enviado para main
#228

[REFACT] (Issue #228) : corrigindo código

---

docs/Tools_Testing.md

Criação da documentação referente às ferramentas utilizadas na realização de testes.
#263

[DOC](Issue #263): Documentação das Ferramentas de Testes

---

docs/sprints/sprint13/Time A/Resultado.md

Documento de revisão da sprint 13
#269

[DOC] (Issue #269) : review sprint 13
